config/routes.rb
Rails.application.routes.draw do

  resources :bookings, only: [:new, :create]
  resources :cars, only: [:show, :index]

  post '/cars' => 'cars#index'
  get '/bookings/:car_id/:booking_id' => 'bookings#show'

  root 'bookings#new'

end

app/models/booking.rb
class Booking
  include Mongoid::Document

  # Constant mapping of available pickup / return locations
  LOCATIONS = { 
    1 => 'Vienna central', 
    2 => 'Vienna airport',
    3 => 'Vienna station' 
  }

  # Fields
  field :pickup_datetime, type: DateTime
  field :return_datetime, type: DateTime
  field :pickup_location, type: Integer
  field :return_location, type: Integer

  # Relations
  embedded_in :car

  # Validations
  validates_presence_of :pickup_datetime, :return_datetime, :pickup_location, :return_location, :car
  validate :pickup_before_return_validation
  validate :car_is_available_validation
  %w(pickup return).each { |prefix| validate "#{prefix}_location_exists_validation".to_sym }

  # Custom getters / setters
  %w(pickup return).each do |prefix|                    # Get location na" }basing on id
    define_method "#{prefix}_location_name" do
      LOCATIONS[read_attribute("#{prefix}_location")]
    end
  end

  # Methods
  def total_price
    if car.present?
      (car.price / 3 * (return_datetime - pickup_datetime).to_i).to_i
    end
  end


  private
  def pickup_before_return_validation
    if pickup_datetime.present? && return_datetime.present? && pickup_datetime >= return_datetime
      errors.add(:pickup_datetime, 'should be before return_datetime')
    end
  end

  # Validation of pickup / return location
  %w(pickup return).each do |prefix|
    define_method "#{prefix}_location_exists_validation" do
      if read_attribute("#{prefix}_location").present? && LOCATIONS[read_attribute("#{prefix}_location")].nil?
        errors.add("#{prefix}_location".to_sym, "isn't available location")
      end
    end
  end

  def car_is_available_validation
    if car.present? && pickup_datetime.present? && return_datetime.present? &&
      !car.available_in?(pickup_datetime, return_datetime)
        errors.add(:car, "you chose isn't available")
      end
  end
end

app/models/car.rb
class Car
  include Mongoid::Document

  # Fields
  field :price, type: Float
  field :name, type: String
  field :people_number, type: Integer
  field :luggage_number, type: Integer
  field :doors_number, type: Integer

  # Relations
  embeds_many :bookings

  # Uploaders
  mount_uploader :photo, PhotoUploader

  # Validations
  validates_presence_of :price, :name, :people_number, :luggage_number, :doors_number
  validates_numericality_of :people_number, :luggage_number, :doors_number, greater_than: 0, only_integer: true
  validates_numericality_of :price, greater_than: 0

  # Methods
  def available_in? new_pickup, new_return
    bookings.or({:pickup_datetime.gt => new_return}, {:return_datetime.lt => new_pickup}).count == bookings.count
  end

  # Static methods
  def self.available_in new_pickup, new_return
    all.to_a.select { |c| c.available_in?(new_pickup, new_return) }
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    render layout: false
  end

  def create
    @car = Car.find(params[:car_id])
    @booking = @car.bookings.build(session[:booking])
    redirect_to root_url if @booking.nil?
    if @booking.save
      flash[:success] = "You have chosen a #{@booking.car.name}"

      # Keeping it to know which booking is current
      session[:booking_id] = @booking.id.to_s
      session[:car_id] = @car.id.to_s

      redirect_to url_for(controller: :bookings, action: :show, car_id: @car.id.to_s, booking_id: @booking.id.to_s)
    end
  end

  def show
    @car = Car.find(params[:car_id])
    @booking = @car.bookings.find(params[:booking_id])
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_filter :set_booking

  def index
    pickup_dt = @booking.try(:pickup_datetime)
    return_dt = @booking.try(:return_datetime)
    @cars = Car.available_in(pickup_dt, return_dt)
  end

  def show
    @car = Car.find(params[:id])
    session[:car_id] = @car.id.to_s
  end

  private
  def booking_params
    params.require(:booking).permit(:pickup_datetime, :return_datetime, :pickup_location, :return_location)
  end

  def set_booking
    if params[:booking].present?
      session[:booking] = booking_params
    end
    @booking = Booking.new(session[:booking])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_booking_url
    if session[:car_id].present? && session[:booking_id].present?
      url_for(controller: :bookings, action: :show, car_id: session[:car_id], booking_id: session[:booking_id])
    else
      '#'
    end
  end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/bookings/new.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title SiTryout
    = stylesheet_link_tag    'index', media: 'all', 'data-turbolinks-track' => true
    = stylesheet_link_tag 'http://fonts.googleapis.com/css?family=Open+Sans:400,700,300', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'index', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    #car-slides
      #car-slide1.slide.active
      #car-slide2.slide
    #wrapper
      #aperture
      #header
        #logo
          = link_to root_url do
            = image_tag 'logo.png'
        %ul#header-menu
          %li= link_to 'Aktuelle Buchung', current_booking_url
          %li= link_to 'FAQ / Hilfe', '#'
      #new-booking
        %h1 Nutze die Brückentage mit Carmunio.
        = form_for :booking, url: url_for(controller: 'cars', action: 'index') do |f|
          = f.select :pickup_location do
            = options_for_select Booking::LOCATIONS.invert.to_a
          = f.select :return_location do
            = options_for_select Booking::LOCATIONS.invert.to_a
          = f.text_field :pickup_datetime, placeholder: 'Zeit der Abholung', class: "datetime"
          = f.text_field :return_datetime, placeholder: 'Zeir der Rückgabe', class: "datetime"
          = f.submit "Zur Fahrzeugwahl"
  :javascript
    new Window.NewBooking();

app/views/bookings/show.html.haml
%ul#steps
  %li.first Fahrzeugwahl
  %li.connector
  %li.second.active Extras
#car-details
  = image_tag @booking.car.photo.url
  %h1= @booking.car.name
  3 Tage Wien für
  .price= "#{@car.price} €"

app/views/cars/index.html.haml
%ul#steps
  %li.first.active Fahrzeugwahl
  %li.connector
  %li.second Extras
#cars-list
  - @cars.each do |car|
    .car-item
      .car-information
        %h2= car.name
        3 Tage Wien für
        .car-price
          = "#{car.price} €"
        .car-parameters
          .icon.people= "&times;#{car.people_number}".html_safe
          .icon.luggage= "&times;#{car.luggage_number}".html_safe
          .icon.doors= "&times;#{car.doors_number}".html_safe
        %ul.car-additional
          %li 
            Versicherung inklusiv
            .icon.info
          %li 
            Klare Tankreglung inklusiv
            .icon.info
          %li 
            Unbegrentze Kilometer inklusiv
            .icon.info

        = link_to bookings_url(car_id: car.id.to_s), method: :post, class: 'car-book-button' do
          .header
            Fahrzeug wählen
          .subheader
            = "Garantiert ein #{car.name}"
        
      .car-photo
        = image_tag car.photo.url(:medium)
        = link_to "Gerantiert ein #{car.name}", bookings_url(car_id: car.id.to_s), method: :post, class: 'triangle-button'

      .clearer

app/views/cars/show.html.haml
%ul#steps
  %li.first Fahrzeugwahl
  %li.connector
  %li.second.active Extras
#car-details
  = image_tag @car.photo.url
  = link_to "Gerantiert ein #{@car.name}", bookings_url, class: 'triangle-button', method: :post
  %h1= @car.name
  3 Tage Wien für
  .price= "#{@car.price} €"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title SiTryout
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = stylesheet_link_tag 'http://fonts.googleapis.com/css?family=Open+Sans:400,700,300', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    #header
      #logo
        = link_to root_url do
          = image_tag 'logo.png'
      - if @booking.present?
        #booking-info
          .border
          .info
            .title
              Abholung
            .time
              = l(@booking.pickup_datetime)
            .location
              = @booking.pickup_location_name
          .connector →
          .info
            .title
              Rückgabe
            .time
              = l(@booking.return_datetime)
            .location
              = @booking.return_location_name
          .border
            - if @booking.total_price.present?
              .info
                .price= "#{@booking.total_price} €"
          .clearer
        %ul#booking-additional
          %li Versicherung inklusiv
          %li Klare Tankreglung inklusiv
          %li Unbegrentze Kilometer inklusiv
        
        - if flash[:success].present?
          .notification= flash[:success]

    = yield